create table if not exists public.user_preferences (
  user_id bigint primary key references public.users(user_id) on delete cascade,
  budget_min int check (budget_min is null or budget_min >= 0),
  budget_max int check (budget_max is null or budget_max >= 0),
  updated_at timestamptz not null default now(),
  constraint user_preferences_budget_range_check
    check (budget_min is null or budget_max is null or budget_min <= budget_max)
);

create table if not exists public.reviews (
  review_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  menu_id bigint not null references public.menus(menu_id) on delete cascade,
  rating int not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_menu_interactions (
  interaction_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  menu_id bigint not null references public.menus(menu_id) on delete cascade,
  interaction_type text not null
    check (interaction_type in ('view', 'like', 'pick', 'dislike', 'bookmark')),
  created_at timestamptz not null default now()
);

create table if not exists public.personal_recommendation_runs (
  run_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  algorithm_version text not null default 'personal-weighted-v1',
  config_json jsonb,
  generated_at timestamptz not null default now()
);

create table if not exists public.personal_recommendation_results (
  result_id bigint generated by default as identity primary key,
  run_id bigint not null references public.personal_recommendation_runs(run_id) on delete cascade,
  menu_id bigint not null references public.menus(menu_id) on delete cascade,
  rank_no int not null check (rank_no > 0),
  total_score numeric(5, 2) not null check (total_score >= 0 and total_score <= 100),
  scores_json jsonb,
  reason text,
  is_new_suggestion boolean not null default false,
  unique (run_id, rank_no),
  unique (run_id, menu_id)
);

alter table public.personal_recommendation_results
  add column if not exists scores_json jsonb;

alter table public.meal_history
  add column if not exists personal_recommendation_run_id bigint
  references public.personal_recommendation_runs(run_id) on delete set null;

create index if not exists user_preferences_user_id_idx
  on public.user_preferences(user_id);
create index if not exists reviews_menu_id_idx
  on public.reviews(menu_id);
create index if not exists reviews_user_id_menu_id_idx
  on public.reviews(user_id, menu_id);
create index if not exists user_menu_interactions_user_id_idx
  on public.user_menu_interactions(user_id);
create index if not exists user_menu_interactions_menu_id_idx
  on public.user_menu_interactions(menu_id);
create index if not exists user_menu_interactions_interaction_type_idx
  on public.user_menu_interactions(interaction_type);
create index if not exists user_menu_interactions_created_at_idx
  on public.user_menu_interactions(created_at);
create index if not exists user_menu_interactions_user_id_menu_id_idx
  on public.user_menu_interactions(user_id, menu_id);
create index if not exists user_menu_interactions_user_type_created_idx
  on public.user_menu_interactions(user_id, interaction_type, created_at);
create index if not exists user_menu_interactions_menu_type_idx
  on public.user_menu_interactions(menu_id, interaction_type);
create index if not exists personal_recommendation_runs_user_id_generated_at_idx
  on public.personal_recommendation_runs(user_id, generated_at desc);
create index if not exists personal_recommendation_results_run_id_idx
  on public.personal_recommendation_results(run_id);
create index if not exists personal_recommendation_results_run_id_rank_no_idx
  on public.personal_recommendation_results(run_id, rank_no);
create index if not exists personal_recommendation_results_menu_id_idx
  on public.personal_recommendation_results(menu_id);

drop trigger if exists set_user_preferences_updated_at on public.user_preferences;
create trigger set_user_preferences_updated_at
before update on public.user_preferences
for each row execute function public.set_updated_at();

grant select, insert, update, delete on
  public.user_preferences,
  public.reviews,
  public.user_menu_interactions,
  public.personal_recommendation_runs,
  public.personal_recommendation_results
to authenticated;

grant usage, select on all sequences in schema public to authenticated;

alter table public.user_preferences enable row level security;
alter table public.reviews enable row level security;
alter table public.user_menu_interactions enable row level security;
alter table public.personal_recommendation_runs enable row level security;
alter table public.personal_recommendation_results enable row level security;

drop policy if exists "Users can manage own recommendation preferences" on public.user_preferences;
create policy "Users can manage own recommendation preferences"
on public.user_preferences for all
to authenticated
using (user_id = (select public.current_user_id()))
with check (user_id = (select public.current_user_id()));

drop policy if exists "Users can manage own reviews" on public.reviews;
create policy "Users can manage own reviews"
on public.reviews for all
to authenticated
using (user_id = (select public.current_user_id()))
with check (user_id = (select public.current_user_id()));

drop policy if exists "Authenticated users can read reviews" on public.reviews;
create policy "Authenticated users can read reviews"
on public.reviews for select
to authenticated
using (true);

drop policy if exists "Users can insert own menu interactions" on public.user_menu_interactions;
create policy "Users can insert own menu interactions"
on public.user_menu_interactions for insert
to authenticated
with check (user_id = (select public.current_user_id()));

drop policy if exists "Users can read own menu interactions" on public.user_menu_interactions;
create policy "Users can read own menu interactions"
on public.user_menu_interactions for select
to authenticated
using (user_id = (select public.current_user_id()));

drop policy if exists "Users can read own personal recommendation runs" on public.personal_recommendation_runs;
create policy "Users can read own personal recommendation runs"
on public.personal_recommendation_runs for select
to authenticated
using (user_id = (select public.current_user_id()));

drop policy if exists "Users can create own personal recommendation runs" on public.personal_recommendation_runs;
create policy "Users can create own personal recommendation runs"
on public.personal_recommendation_runs for insert
to authenticated
with check (user_id = (select public.current_user_id()));

drop policy if exists "Users can read own personal recommendation results" on public.personal_recommendation_results;
create policy "Users can read own personal recommendation results"
on public.personal_recommendation_results for select
to authenticated
using (
  exists (
    select 1
    from public.personal_recommendation_runs prr
    where prr.run_id = personal_recommendation_results.run_id
      and prr.user_id = (select public.current_user_id())
  )
);

drop policy if exists "Users can create own personal recommendation results" on public.personal_recommendation_results;
create policy "Users can create own personal recommendation results"
on public.personal_recommendation_results for insert
to authenticated
with check (
  exists (
    select 1
    from public.personal_recommendation_runs prr
    where prr.run_id = personal_recommendation_results.run_id
      and prr.user_id = (select public.current_user_id())
  )
);
