create schema if not exists private;

revoke all on schema private from public;
revoke all on schema private from anon;
revoke all on schema private from authenticated;

create table if not exists public.users (
  user_id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  email varchar(100) not null unique,
  password_hash varchar(255),
  nickname varchar(50) not null,
  user_type varchar(20),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on column public.users.password_hash is
  'Unused when Supabase Auth stores credentials. Kept nullable for DB schema compatibility.';

create table if not exists public.menu_categories (
  category_id bigint generated by default as identity primary key,
  name varchar(50) not null unique
);

create table if not exists public.menus (
  menu_id bigint generated by default as identity primary key,
  category_id bigint not null references public.menu_categories(category_id) on delete restrict,
  name varchar(100) not null unique,
  description text,
  spicy_level int not null default 0 check (spicy_level between 0 and 5),
  price_level int check (price_level between 1 and 5),
  calorie int check (calorie is null or calorie >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.tags (
  tag_id bigint generated by default as identity primary key,
  name varchar(50) not null unique
);

create table if not exists public.category_tags (
  category_id bigint not null references public.menu_categories(category_id) on delete cascade,
  tag_id bigint not null references public.tags(tag_id) on delete cascade,
  primary key (category_id, tag_id)
);

create table if not exists public.menu_tags (
  menu_id bigint not null references public.menus(menu_id) on delete cascade,
  tag_id bigint not null references public.tags(tag_id) on delete cascade,
  primary key (menu_id, tag_id)
);

create table if not exists public.user_menu_preferences (
  user_id bigint not null references public.users(user_id) on delete cascade,
  menu_id bigint not null references public.menus(menu_id) on delete cascade,
  preference_score int not null check (preference_score between -5 and 5),
  updated_at timestamptz not null default now(),
  primary key (user_id, menu_id)
);

create table if not exists public.user_category_preferences (
  user_id bigint not null references public.users(user_id) on delete cascade,
  category_id bigint not null references public.menu_categories(category_id) on delete cascade,
  preference_score int not null check (preference_score between -5 and 5),
  updated_at timestamptz not null default now(),
  primary key (user_id, category_id)
);

create table if not exists public.user_tag_preferences (
  user_id bigint not null references public.users(user_id) on delete cascade,
  tag_id bigint not null references public.tags(tag_id) on delete cascade,
  preference_score int not null check (preference_score between -5 and 5),
  updated_at timestamptz not null default now(),
  primary key (user_id, tag_id)
);

create table if not exists public.allergies (
  allergy_id bigint generated by default as identity primary key,
  name varchar(50) not null unique
);

create table if not exists public.user_allergies (
  user_id bigint not null references public.users(user_id) on delete cascade,
  allergy_id bigint not null references public.allergies(allergy_id) on delete cascade,
  primary key (user_id, allergy_id)
);

create table if not exists public.menu_allergies (
  menu_id bigint not null references public.menus(menu_id) on delete cascade,
  allergy_id bigint not null references public.allergies(allergy_id) on delete cascade,
  primary key (menu_id, allergy_id)
);

create table if not exists public.meeting_purposes (
  meeting_purpose_id bigint generated by default as identity primary key,
  name varchar(30) not null unique
);

create table if not exists public.menu_purpose_suitability (
  menu_id bigint not null references public.menus(menu_id) on delete cascade,
  meeting_purpose_id bigint not null references public.meeting_purposes(meeting_purpose_id) on delete cascade,
  suitability_score int not null check (suitability_score between 0 and 5),
  primary key (menu_id, meeting_purpose_id)
);

create table if not exists public.meal_history (
  history_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  menu_id bigint not null references public.menus(menu_id) on delete restrict,
  eaten_at timestamptz not null default now(),
  rating int check (rating between 1 and 5),
  memo text,
  created_at timestamptz not null default now()
);

create table if not exists public.meetings (
  meeting_id bigint generated by default as identity primary key,
  title varchar(100),
  meeting_time timestamptz not null,
  meeting_purpose_id bigint not null references public.meeting_purposes(meeting_purpose_id) on delete restrict,
  location varchar(255),
  created_by bigint not null references public.users(user_id) on delete cascade,
  selected_menu_id bigint references public.menus(menu_id) on delete set null,
  status varchar(20) not null default 'CREATED'
    check (status in ('CREATED', 'COLLECTING', 'RECOMMENDED', 'DECIDED', 'CLOSED')),
  created_at timestamptz not null default now()
);

create table if not exists public.meeting_participants (
  participant_id bigint generated by default as identity primary key,
  meeting_id bigint not null references public.meetings(meeting_id) on delete cascade,
  user_id bigint references public.users(user_id) on delete set null,
  display_name varchar(50) not null,
  attendance_status varchar(20) not null default 'PENDING'
    check (attendance_status in ('JOINED', 'PENDING', 'DECLINED')),
  joined_at timestamptz,
  created_at timestamptz not null default now(),
  unique (meeting_id, user_id)
);

create table if not exists public.recommendation_runs (
  run_id bigint generated by default as identity primary key,
  meeting_id bigint not null references public.meetings(meeting_id) on delete cascade,
  algorithm_version varchar(30) not null,
  config_json jsonb,
  generated_at timestamptz not null default now()
);

create table if not exists public.meeting_recommendations (
  recommendation_id bigint generated by default as identity primary key,
  run_id bigint not null references public.recommendation_runs(run_id) on delete cascade,
  menu_id bigint not null references public.menus(menu_id) on delete cascade,
  rank_no int not null check (rank_no > 0),
  total_score numeric(5, 2) not null,
  reason text,
  unique (run_id, rank_no),
  unique (run_id, menu_id)
);

create index if not exists users_auth_user_id_idx on public.users(auth_user_id);
create index if not exists menus_category_id_idx on public.menus(category_id);
create index if not exists category_tags_tag_id_idx on public.category_tags(tag_id);
create index if not exists user_menu_preferences_user_id_idx on public.user_menu_preferences(user_id);
create index if not exists user_category_preferences_user_id_idx on public.user_category_preferences(user_id);
create index if not exists user_tag_preferences_user_id_idx on public.user_tag_preferences(user_id);
create index if not exists user_allergies_user_id_idx on public.user_allergies(user_id);
create index if not exists meal_history_user_id_eaten_at_idx on public.meal_history(user_id, eaten_at desc);
create index if not exists meetings_created_by_idx on public.meetings(created_by);
create index if not exists meeting_participants_meeting_id_idx on public.meeting_participants(meeting_id);
create index if not exists recommendation_runs_meeting_id_generated_at_idx
  on public.recommendation_runs(meeting_id, generated_at desc);
create index if not exists meeting_recommendations_run_id_rank_no_idx
  on public.meeting_recommendations(run_id, rank_no);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_users_updated_at on public.users;
create trigger set_users_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create or replace function private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  insert into public.users (auth_user_id, email, nickname, user_type)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'nickname', split_part(coalesce(new.email, 'user'), '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'user_type', 'PERSONAL')
  )
  on conflict (auth_user_id) do update
    set email = excluded.email,
        nickname = excluded.nickname,
        user_type = excluded.user_type,
        updated_at = now();

  return new;
end;
$$;

revoke all on function private.handle_new_auth_user() from public;
revoke all on function private.handle_new_auth_user() from anon;
revoke all on function private.handle_new_auth_user() from authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_auth_user();

create or replace function public.current_user_id()
returns bigint
language sql
stable
set search_path = public
as $$
  select user_id
  from public.users
  where auth_user_id = (select auth.uid())
  limit 1
$$;

revoke all on function public.current_user_id() from public;
grant execute on function public.current_user_id() to authenticated;

grant usage on schema public to anon, authenticated;

grant select on
  public.menu_categories,
  public.menus,
  public.tags,
  public.category_tags,
  public.menu_tags,
  public.allergies,
  public.menu_allergies,
  public.meeting_purposes,
  public.menu_purpose_suitability
to authenticated;

grant select, insert, update, delete on
  public.users,
  public.user_menu_preferences,
  public.user_category_preferences,
  public.user_tag_preferences,
  public.user_allergies,
  public.meal_history,
  public.meetings,
  public.meeting_participants,
  public.recommendation_runs,
  public.meeting_recommendations
to authenticated;

grant usage, select on all sequences in schema public to authenticated;
alter default privileges in schema public grant usage, select on sequences to authenticated;

alter table public.users enable row level security;
alter table public.menu_categories enable row level security;
alter table public.menus enable row level security;
alter table public.tags enable row level security;
alter table public.category_tags enable row level security;
alter table public.menu_tags enable row level security;
alter table public.user_menu_preferences enable row level security;
alter table public.user_category_preferences enable row level security;
alter table public.user_tag_preferences enable row level security;
alter table public.allergies enable row level security;
alter table public.user_allergies enable row level security;
alter table public.menu_allergies enable row level security;
alter table public.meeting_purposes enable row level security;
alter table public.menu_purpose_suitability enable row level security;
alter table public.meal_history enable row level security;
alter table public.meetings enable row level security;
alter table public.meeting_participants enable row level security;
alter table public.recommendation_runs enable row level security;
alter table public.meeting_recommendations enable row level security;

drop policy if exists "Users can read own profile" on public.users;
create policy "Users can read own profile"
on public.users for select
to authenticated
using ((select auth.uid()) = auth_user_id);

drop policy if exists "Users can update own profile" on public.users;
create policy "Users can update own profile"
on public.users for update
to authenticated
using ((select auth.uid()) = auth_user_id)
with check ((select auth.uid()) = auth_user_id);

drop policy if exists "Authenticated users can read menu categories" on public.menu_categories;
create policy "Authenticated users can read menu categories"
on public.menu_categories for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read menus" on public.menus;
create policy "Authenticated users can read menus"
on public.menus for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read tags" on public.tags;
create policy "Authenticated users can read tags"
on public.tags for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read category tags" on public.category_tags;
create policy "Authenticated users can read category tags"
on public.category_tags for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read menu tags" on public.menu_tags;
create policy "Authenticated users can read menu tags"
on public.menu_tags for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read allergies" on public.allergies;
create policy "Authenticated users can read allergies"
on public.allergies for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read menu allergies" on public.menu_allergies;
create policy "Authenticated users can read menu allergies"
on public.menu_allergies for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read meeting purposes" on public.meeting_purposes;
create policy "Authenticated users can read meeting purposes"
on public.meeting_purposes for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read menu purpose suitability" on public.menu_purpose_suitability;
create policy "Authenticated users can read menu purpose suitability"
on public.menu_purpose_suitability for select
to authenticated
using (true);

drop policy if exists "Users can read own menu preferences" on public.user_menu_preferences;
create policy "Users can read own menu preferences"
on public.user_menu_preferences for select
to authenticated
using (user_id = (select public.current_user_id()));

drop policy if exists "Users can insert own menu preferences" on public.user_menu_preferences;
create policy "Users can insert own menu preferences"
on public.user_menu_preferences for insert
to authenticated
with check (user_id = (select public.current_user_id()));

drop policy if exists "Users can update own menu preferences" on public.user_menu_preferences;
create policy "Users can update own menu preferences"
on public.user_menu_preferences for update
to authenticated
using (user_id = (select public.current_user_id()))
with check (user_id = (select public.current_user_id()));

drop policy if exists "Users can delete own menu preferences" on public.user_menu_preferences;
create policy "Users can delete own menu preferences"
on public.user_menu_preferences for delete
to authenticated
using (user_id = (select public.current_user_id()));

drop policy if exists "Users can manage own category preferences" on public.user_category_preferences;
create policy "Users can manage own category preferences"
on public.user_category_preferences for all
to authenticated
using (user_id = (select public.current_user_id()))
with check (user_id = (select public.current_user_id()));

drop policy if exists "Users can manage own tag preferences" on public.user_tag_preferences;
create policy "Users can manage own tag preferences"
on public.user_tag_preferences for all
to authenticated
using (user_id = (select public.current_user_id()))
with check (user_id = (select public.current_user_id()));

drop policy if exists "Users can manage own allergies" on public.user_allergies;
create policy "Users can manage own allergies"
on public.user_allergies for all
to authenticated
using (user_id = (select public.current_user_id()))
with check (user_id = (select public.current_user_id()));

drop policy if exists "Users can manage own meal history" on public.meal_history;
create policy "Users can manage own meal history"
on public.meal_history for all
to authenticated
using (user_id = (select public.current_user_id()))
with check (user_id = (select public.current_user_id()));

drop policy if exists "Users can read own meetings" on public.meetings;
create policy "Users can read own meetings"
on public.meetings for select
to authenticated
using (created_by = (select public.current_user_id()));

drop policy if exists "Users can create meetings" on public.meetings;
create policy "Users can create meetings"
on public.meetings for insert
to authenticated
with check (created_by = (select public.current_user_id()));

drop policy if exists "Creators can update meetings" on public.meetings;
create policy "Creators can update meetings"
on public.meetings for update
to authenticated
using (created_by = (select public.current_user_id()))
with check (created_by = (select public.current_user_id()));

drop policy if exists "Users can read related participants" on public.meeting_participants;
create policy "Users can read related participants"
on public.meeting_participants for select
to authenticated
using (
  user_id = (select public.current_user_id())
  or exists (
    select 1
    from public.meetings m
    where m.meeting_id = meeting_participants.meeting_id
      and m.created_by = (select public.current_user_id())
  )
);

drop policy if exists "Meeting creators can insert participants" on public.meeting_participants;
create policy "Meeting creators can insert participants"
on public.meeting_participants for insert
to authenticated
with check (
  exists (
    select 1
    from public.meetings m
    where m.meeting_id = meeting_participants.meeting_id
      and m.created_by = (select public.current_user_id())
  )
);

drop policy if exists "Meeting creators and participants can update participants" on public.meeting_participants;
create policy "Meeting creators and participants can update participants"
on public.meeting_participants for update
to authenticated
using (
  user_id = (select public.current_user_id())
  or exists (
    select 1
    from public.meetings m
    where m.meeting_id = meeting_participants.meeting_id
      and m.created_by = (select public.current_user_id())
  )
)
with check (
  user_id = (select public.current_user_id())
  or exists (
    select 1
    from public.meetings m
    where m.meeting_id = meeting_participants.meeting_id
      and m.created_by = (select public.current_user_id())
  )
);

drop policy if exists "Creators can manage recommendation runs" on public.recommendation_runs;
create policy "Creators can manage recommendation runs"
on public.recommendation_runs for all
to authenticated
using (
  exists (
    select 1
    from public.meetings m
    where m.meeting_id = recommendation_runs.meeting_id
      and m.created_by = (select public.current_user_id())
  )
)
with check (
  exists (
    select 1
    from public.meetings m
    where m.meeting_id = recommendation_runs.meeting_id
      and m.created_by = (select public.current_user_id())
  )
);

drop policy if exists "Creators can manage meeting recommendations" on public.meeting_recommendations;
create policy "Creators can manage meeting recommendations"
on public.meeting_recommendations for all
to authenticated
using (
  exists (
    select 1
    from public.recommendation_runs rr
    join public.meetings m on m.meeting_id = rr.meeting_id
    where rr.run_id = meeting_recommendations.run_id
      and m.created_by = (select public.current_user_id())
  )
)
with check (
  exists (
    select 1
    from public.recommendation_runs rr
    join public.meetings m on m.meeting_id = rr.meeting_id
    where rr.run_id = meeting_recommendations.run_id
      and m.created_by = (select public.current_user_id())
  )
);
